### ISSUE TITLE
Return advertised services when scanning

### ISSUE THREAD

**Issue by mikkeldamsgaard** [OpenBluetoothToolbox/SimpleBLE#100]
Advertised data has the option to include service UUIDS.

These would be great to get back in discovered peripheral. These are different from the service ids queried when connected, so should be in a different attribute

**Comment by kdewald** [comment]
Hey @mikkeldamsgaard, thanks for the suggestion! Will add it to the to-do list.

**Comment by kdewald** [comment]
Implemented in https://github.com/OpenBluetoothToolbox/SimpleBLE/pull/130
