### ISSUE TITLE
Python Read Example out of date - 'method' object is not iterable

### ISSUE THREAD

**Issue by Carl-CWX** [OpenBluetoothToolbox/SimpleBLE#118]
https://github.com/OpenBluetoothToolbox/SimpleBLE/blob/5da893162f0969e0e25bdd3194655b6fd6f4e899/examples/simplepyble/read.py#L42

Release notes mention a change, 
Python example crashes with the exception "'method' object is not iterable" while attempting to iterate around the device characteristics when testing on Windows,

**Comment by felixdollack** [comment]
I just encountered the same issue.
Using
```
for characteristic in service.characteristics():
```
works.

**Comment by kdewald** [comment]
I just uploaded a fix and added some unit tests to protect against this in the future.
Thanks for the report!
