### ISSUE TITLE
Advertising name not available

### ISSUE THREAD

**Issue by didjado** [OpenBluetoothToolbox/SimpleBLE#122]
I dont think im missing anything but it seams under python on windows10 the advertising name is not available

**Comment by kdewald** [comment]
Hey @didjado, thanks for the report!

So far I think this bug is related to this issue: https://github.com/OpenBluetoothToolbox/SimpleBLE/issues/111

Can you tell me which device you're looking for? I'm trying to replicate this consistently for testing.

**Comment by didjado** [comment]
Its a custom product with a Nordic service uuid 
nus_service = "6e400001-b5a3-f393-e0a9-e50e24dcca9e"
nus_char_tx = "6e400003-b5a3-f393-e0a9-e50e24dcca9e"
nus_char_rx = "6e400002-b5a3-f393-e0a9-e50e24dcca9e"

**Comment by kdewald** [comment]
Fixed in #128
