### ISSUE TITLE
No simpleble/export.h

### ISSUE THREAD

**Issue by felixdollack** [OpenBluetoothToolbox/SimpleBLE#124]
I am sure I am having a stupid mistake somewhere.
I am trying to compile the following:
```
#include "simpleble/SimpleBLE.h"

int main(int argc, char *argv[]) {
    return 0;
}
```
with `gcc main.cpp -I SimpleBLE/simpleble/include -o main`.

What I end up with is this error:
```
SimpleBLE/simpleble/include/simpleble_c/simpleble.h:3:10: fatal error: 'simpleble/export.h' file not found
#include <simpleble/export.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Checking my local copy of the repository as well as searching the repository yields no results for export.h.

What am I doing wrong here?

**Comment by kdewald** [comment]
Hey @felixdollack, thanks for reaching out!

You're currently trying to use SimpleBLE by compiling directly with GCC, which won't work unless you use the installed version of the library (see: https://simpleble.readthedocs.io/en/latest/simpleble/usage.html) The `export.h` file is autogenerated by CMake, it will appear when you follow those instructions.

It's better if you use CMake as part of your build system if you plan on using SimpleBLE. Following the examples might be an easier starting point.
