### ISSUE TITLE
Memory error free `simpleble_peripheral_address`

### ISSUE THREAD

**Issue by Andrey1994** [OpenBluetoothToolbox/SimpleBLE#13]
I am not 100% sure and cannot find the exact issue but when I run smth very similar to connect_c sample with the debugger in VS I get this assert. 
![image](https://user-images.githubusercontent.com/8217521/134600278-40a743ff-ae5c-4be0-8888-13667f7b5d2e.png)

**Comment by Andrey1994** [comment]
![image](https://user-images.githubusercontent.com/8217521/134600587-fe9ebc39-9c85-4480-bcb6-24839e78c553.png)

**Comment by Andrey1994** [comment]
I found a hint but dont know the best solution for it... Take a look at this answer https://stackoverflow.com/a/35311928 

I am linking MSVC runtime statically because this way users who use precompiled libs(majority of users in fact) don't need to install C++ redist package.

Potential solutions:

* stop using static linking of MSVC runtime(not an option in fact, I don't want to force users to install extra packages, especially when before they didn't have to)
* As this guy proposed "You could get that work even with /MT, but that is more difficult - you would need to provide some interface which will allow the objects allocated in the DLL to be deallocated there as well. " The question is should I do it only in my project or it should be in SimpleBLE upstream?

**Comment by Andrey1994** [comment]
Or maybe it would be better to change API to allocate memory outside SimpleBLE dll
Now: 
```
char * simpleble_peripheral_address (simpleble_peripheral_t handle)
```
After this change:
```
size_t simpleble_peripheral_address (simpleble_peripheral_t handle, char *address_output, size_t max_size) // return actual size
```

And do the same for all other methods

**Comment by kdewald** [comment]
I think it might be better to add a `simpleble_free` method. I'll add that asap.

**Comment by kdewald** [comment]
I just added the `simpleble_free` method, let me know if you see any additional issues.

**Comment by Andrey1994** [comment]
it helped, now it works fine, thanks
