### ISSUE TITLE
Attempting to write to descriptor fails

### ISSUE THREAD

**Issue by sundarhigher** [OpenBluetoothToolbox/SimpleBLE#137]
When I try to write to the CCD 00002902-0000-1000-8000-00805f9b34fb to enable notifications for a characteristic that has the descriptor it fails and throws the following error
terminate called after throwing an instance of 'SimpleDBus::Exception::SendFailed'
  what():  org.bluez.Error.NotPermitted: Write not permitted
[69] method call[(null)->org.bluez] /org/bluez/hci0/dev_C0_26_DA_0C_17_6A/service001c/char001d/desc001f org.bluez.GattDescriptor1 WriteValue

**Comment by kdewald** [comment]
Hey @sundarhigher, thanks for the report.

The error you are getting comes directly from the operating system, which means the operation you're trying to carry out is not allowed in that way. If you want to enable notifications, you should use the `notify` function of the corresponding characteristic.
