### ISSUE TITLE
Failed to connect to device using examples/connect program on windows 10

### ISSUE THREAD

**Issue by hellozyemlya** [OpenBluetoothToolbox/SimpleBLE#157]
On windows 10 connect always gives "A method was called at an unexpected time." error when trying to connect to device.
Device is custom one, nrf based.

**Comment by kdewald** [comment]
Hey @hellozyemlya, thanks for the report.

What version of the library gave you this error?

**Comment by hellozyemlya** [comment]
It was latest master branch.

**Comment by kdewald** [comment]
Can you try the code from this MR to see if it makes things better? https://github.com/OpenBluetoothToolbox/SimpleBLE/pull/166

**Comment by kdewald** [comment]
Hey @hellozyemlya, I'm not sure if we talked about this over Discord or if it was somebody else.

When dealing with custom firmware, it is possible (especially on older SDKs) for the firmware to cause this issue on the host. A few things have been changed recently that should make this more stable. I'll close this issue but feel free to reopen if it's still happening.
