### ISSUE TITLE
Can I use this on android?

### ISSUE THREAD

**Issue by BtuApple** [OpenBluetoothToolbox/SimpleBLE#168]
I want use this on android, what need I do?

**Comment by kdewald** [comment]
Hey @BtuApple, thanks for reaching out!

So far there is no support for Android. I plan to get to it at some point, but there's a lot that needs to happen for that (on top of me not being fully familiarized with the environment) so unless lends a helping hand or sponsors the work, it's not happening anytime soon.

**Comment by BtuApple** [comment]
Got it！
