### ISSUE TITLE
Peripheral Identifier not being updated in Windows

### ISSUE THREAD

**Issue by Gnome16** [OpenBluetoothToolbox/SimpleBLE#174]
I have a device where the Identifier isn't included in the advertised data so scanning for the devices doesn't pick up the name. With other software (/nSoftware's BLE) I have to connect and discover services and characteristics for it to update the device name, but with SimpleBLE that still isn't getting it. I think it's related to Windows caching the data, since the other software works fine after the device has been discovered the first time. Is there a way to force the program to re-examine the data for the name? I'm using Erik Lins' Pascal bindings so maybe that is a complication.

I don't know if it's the same problem with Linux as I'm currently having trouble getting anything to work there, but that's because I know almost nothing about Linux....!

Edit: Sorry, I think this might be related to issue #111. I'll try out version 0.6 when it's released.

**Comment by kdewald** [comment]
Hey @Gnome16, this fix has already been landed. If you use any later build, this issue should be solved.

Currently these Pascal bindings are not part of the tools that we support, so apart from reaching out to Erik (@eriklins, tagging you here in case you see this) there isn't much I can do. If there's a significant demand for these specific bindings I can consider adding them as part of our offering, but that isn't the case right now.
