### ISSUE TITLE
Function get_operating_system() is not available in Windows DLL and Linux shared lib.

### ISSUE THREAD

**Issue by eriklins** [OpenBluetoothToolbox/SimpleBLE#187]
When compiling SimpleBLE for Windows x64 as DLL or for Linux x64 as shared lib, the function simpleble_os_t get_operating_system(void); is not included in the DLL, even though it's in the c header file utils.h. However, not the most important function for me, but wondering why it's missing.

**Comment by kdewald** [comment]
Fixed in https://github.com/OpenBluetoothToolbox/SimpleBLE/commit/46925bdaeefb55bb75c2444f6d9a85b697a51c91
