### ISSUE TITLE
Install on Apple silicon

### ISSUE THREAD

**Issue by eloquentarduino** [OpenBluetoothToolbox/SimpleBLE#190]
I installed and run the library correctly on an Intel MacBook. But when I run the same code on Apple silicon, I get the following error.
![IMG-20230205-WA0000](https://user-images.githubusercontent.com/58848053/216811561-644206d3-2ae3-4484-816b-049e4b380c16.jpg)

**Comment by kdewald** [comment]
Hey @eloquentarduino, thanks for the report.

This is a known issue on v0.5, if you install the latest dev version it will be fixed:
`pip install simplepyble==0.6.0.dev4`

**Comment by eloquentarduino** [comment]
Thank you very much for the fast respinse, I will try

Il lun 6 feb 2023, 06:24 Kevin Dewald ***@***.***> ha scritto:
