### ISSUE TITLE
Static and shared build releases are equal

### ISSUE THREAD

**Issue by laborg** [OpenBluetoothToolbox/SimpleBLE#208]
First off, thanks for publishing SimpleBLE as shared lib.
I was looking forward to use them to create Julia bindings, but it turns out that they are equal to the static lib versions.

**Comment by kdewald** [comment]
@laborg thanks for the fix! Can you send me the link to your project so that I can send people your way?

**Comment by laborg** [comment]
@kdewald As soon as they are released I will tag you. The idea is to create two projects: 
 - `SimpleBLE_jll` which makes the shared library available on Julia (see https://docs.binarybuilder.org/stable/jll/) and
 - `SimpleBLE.jl` a Julia package to offer a higher level abstraction for Bluetooth LE calls

**Comment by laborg** [comment]
@kdewald 
The builds for 
 - simpleble_shared_linux-armv6.zip 
 - simpleble_shared_linux-x86.zip 
still include the static libraries. Should CI automatically upload binary artifacts resulting from a merged PR or is there a manual step involved?

**Comment by kdewald** [comment]
@laborg There's something broken in the build process that I still need to debug, so those two will be wrong for a while longer while I figure it out.

**Comment by laborg** [comment]
Could it be that this is a timing problem with parallel builds?

**Comment by kdewald** [comment]
No, this is an architecture problem. CMake tries to link to an incorrect DBus library file. It should be somewhat straightforward to fix.

**Comment by kdewald** [comment]
This was fixed in v0.6.1
