### ISSUE TITLE
Scan Start/Stop problem

### ISSUE THREAD

**Issue by PatrykSajdok** [OpenBluetoothToolbox/SimpleBLE#22]
I think there is a mistake in Adapter.cpp, both `scan_start()` and `scan_stop()` are calling `internal_->scan_start()`
![image](https://user-images.githubusercontent.com/76005511/135224600-9e39c935-a702-44c4-a5b0-3323f0d8f28c.png)

**Comment by kdewald** [comment]
Thanks for the report, I just fixed it!
