### ISSUE TITLE
SimpleBLE C and C++ examples failling in Linux with DBus exception error

### ISSUE THREAD

**Issue by Dharani3110** [OpenBluetoothToolbox/SimpleBLE#220]
I get the below DBus issue when trying to execute examples in **simpleBLE** **c** and **cpp** folders. But **simpledbus** example seems to work.

**My environment:**
**OS:** Ubuntu 22.10 Virtual machine
**Installed packages:** libdbus-1-dev
```
terminate called after throwing an instance of 'SimpleDBus::Exception::DBusException'
what():
org.freedesktop.DBus.Error.MatchRuleNotFound: The given match rule wasn't found and can't be removed
Aborted (core dumped)
```
Please help me in solving this issue.

**Comment by kdewald** [comment]
Hey @Dharani3110, can you check if your BLE adapter is supported in the VM? We've had some issues in the past where the OS doesn't really have access to any outside peripherals.

Also, which VM app are you using? VirtualBox? VMWare?

**Comment by Dharani3110** [comment]
To answer your question, I use Oracle VirtualBox. Let me check if OS has access to outside peripherals and get back.

**Comment by Dharani3110** [comment]
After adding my host bluetooth adaptor to the USB devices of the Ubuntu virtual machine, now I get the "Bluetooth not found" error status instead of the DBus error.

**Comment by kdewald** [comment]
It's quite likely that the virtualization layer is failing to properly expose this to Ubuntu. 

My biggest recommendation would be to try this directly on the host, given that it's already supported.

**Comment by kdewald** [comment]
It's quite likely that the virtualization layer is failing to properly expose this to Ubuntu. 

My biggest recommendation would be to try this directly on the host, given that it's already supported.

**Comment by Dharani3110** [comment]
Sure Thanks!

**Comment by Dharani3110** [comment]
Sure, Thanks for your support!
