### ISSUE TITLE
How do I introduce simpleble to the esp32 project? How should I configure the "CMakeLists" file?

### ISSUE THREAD

**Issue by zhy2020** [OpenBluetoothToolbox/SimpleBLE#230]
Hi,how do I introduce simpleble to the esp32(esp-idf) project? How should I configure the "CMakeLists" file?

**Comment by kdewald** [comment]
Hey @zhy2020, this SimpleBLE library is for desktop use only. You're looking for the MBed version, which can be found here: https://os.mbed.com/teams/mbed-x/code/SimpleBLE/
