### ISSUE TITLE
L2CAP support

### ISSUE THREAD

**Issue by stefnotch** [OpenBluetoothToolbox/SimpleBLE#251]
I was wondering if this library supports L2CAP connections out of the box, or how one would best go about implementing them.

I would love this for my next Bluetooth LE project, but I'm somewhat concerned about how (non)doable L2CAP is on Windows.

**Comment by kdewald** [comment]
Hey @stefnotch, thanks for reaching out!

L2CAP is currently not supported and will require a significant effort to add. Those kinds of endeavors I'm only taking as consulting projects at the moment.
