### ISSUE TITLE
how to create Peripheral by given mac address without scanning?

### ISSUE THREAD

**Issue by holahapi** [OpenBluetoothToolbox/SimpleBLE#260]
in windows 10, python 3.9

i already known the mac address and the characteristics uuid.

can i create the Peripheral object directly with mac address?

**Comment by kdewald** [comment]
Hey @holahapi,

The connection process always involves a scanning phase. You can eventually abstract the functionality that you desire in your own code.

**Comment by holahapi** [comment]
i got it, thank you.
