### ISSUE TITLE
can simpleble support ble broadcast?

### ISSUE THREAD

**Issue by shashenli** [OpenBluetoothToolbox/SimpleBLE#278]
i can use simpleble to scan peripherals but i dont see how to broadcast myself

**Comment by shashenli** [comment]
@kdewald

**Comment by eriklins** [comment]
SimpleBLE currently only support BLE central role i.e., scanning, connecting to peripherals, accessing GATT table etc. No peripheral functionality is implemented (yet).

Peripheral role has already been requested in #99, so this one here should be closed.
