### ISSUE TITLE
this is no manufacturer data in peripheral

### ISSUE THREAD

**Issue by shashenli** [OpenBluetoothToolbox/SimpleBLE#279]
i want to capture airdrop(Apple's tech) BLE broadcast , there should be manufacturer data but i cant get it when i use Peripheral::manufacturer_data(). this is a bug

**Comment by shashenli** [comment]
@kdewald @eriklins

**Comment by eriklins** [comment]
Maybe check existing open issues which mention manufacturer data (there are some) and check whether your issue could be related to one of these.

I do not have issues receiving Apple BLE advertisements and can see lots of Apple devices around along with manufacturer specific data, see screenshot (https://github.com/eriklins/InsideBlue-BLE-Tool).

![2023-12-05 11_11_38-Window](https://github.com/OpenBluetoothToolbox/SimpleBLE/assets/35079932/6c000048-6a1f-4de0-9cc5-fb1f756e23a3)

**Comment by eriklins** [comment]
Yes, see project derscription.

**Comment by shashenli** [comment]
> Yes, see project derscription.
it definitely is a bug, i cant get manufacturer data when i use Adapter::scan_for();
so i  tried anohter funcion Adapter::start_scan(),in this case i can get manufacturer data.
