### ISSUE TITLE
 SimpleBLE v0.6.1 - MacOS writeCommand Failing

### ISSUE THREAD

**Issue by L4m4L** [OpenBluetoothToolbox/SimpleBLE#294]
Hello, 

I am trying to integrate a Java macOS BLE library (https://github.com/youxingz/javablex) into a plugin I am writing. I believe this library uses SimpleBLE version 0.6.1 or earlier to provide the native interface to Java. 

I can successfully discover and connect to peripherals using this library, however if I try to write to a characteristic (using the writeCommand or writeRequest functions), the program crashes with the error: 

`libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc`

I think this error is originating from the SimpleBLE side, rather than "javablex", as far as I can tell I am passing all the arguments correctly to the Java library and am sending valid data across to my device. 

I was just wondering if anyone else has had similar issues writing data using the SimpleBLE plugin on macOS and if there is anything I could try to resolve this?

Appreciate any advice that could be given. Thanks!!

**Comment by kdewald** [comment]
Lots has changed since v0.6.1, so I can't answer if other libraries are having issues with older versions.

We have an official Java version of SimpleBLE in the works, but we're still a few months out.
