### ISSUE TITLE
Android scan not working

### ISSUE THREAD

**Issue by Coimbra1984** [OpenBluetoothToolbox/SimpleBLE#300]
Hi,

I built the android branch and created a dart ffi wrapper around the library. It works well on a windows and linux host, but when I scan for peripherals on android, I get 1 device and then nothing more happens. Looking into the code, do I understand it right that the android side is not implemented (yet)?

Best regards,

Markus

**Comment by kdewald** [comment]
The Android branch is still in a very early stage and less than 10% complete. Please wait until the official release.

**Comment by Coimbra1984** [comment]
ok, thanks. If it helps, I found an implementation here: https://github.com/freeors/SDL/blob/master/SDL2-2.0.8/src/peripheral/android/SDL_sysble.c
