### ISSUE TITLE
got Segmentation fault when execute peripheral.write_request using simplepytble in windows

### ISSUE THREAD

**Issue by YFJiang** [OpenBluetoothToolbox/SimpleBLE#312]
when i try to send "680313000a0000000000000000000000000a09696e7374616c6c657212063234383931305f34", i got  Segmentation fault,

here is my simplepyble version
$  pip show simplepyble
Name: simplepyble
Version: 0.7.3
Summary: The ultimate fully-fledged cross-platform BLE library, designed for simplicity and ease of use.

What else is needed? Thanks

**Comment by bramd** [comment]
I also have crashes using SimplePyBLE in a Windows app. This is part of a large and complex application and based on the crashdump I can't determine what exactly is causing the crash/when it happens. So it might be related.

**Comment by kdewald** [comment]
@bramd @YFJiang I've just landed some changes around GIL handling that might be related. Feel free to reopen the issue if installing from source doesn't solve the issue.
