### ISSUE TITLE
Pairing devices

### ISSUE THREAD

**Issue by PatrykSajdok** [OpenBluetoothToolbox/SimpleBLE#32]
Is it possible to pair device using this library? I need to get data from some devices and if I will not add them using Windows bluetooth management, I cannot get anything from them

**Comment by kdewald** [comment]
@PatrykSajdok good news on this issue! I've investigated how to get this to work and found the following:
- On all operating systems, initiating a connection procedure will automatically run pairing if necessary. **This process is entirely managed by the operating system**, there isn't much that we can do from the user side. This has the following implications:
  - The user will need to manually confirm pairing, until that happens no successful access to protected characteristics is possible.
  - Removing a device can only be done from the OS settings page.
  - You cannot know if a device has been paired or not.
  - You cannot access a list of paired devices.
  - There is no programmatic way of controlling this process.
- Linux does allow this, but needs a bit of extra scaffolding that I'll implement in part with SimpleBluez.

I'm actively working on this right now, I hope to have a documented release on this topic soon.
