### ISSUE TITLE
Shopping lists of new features/improvements

### ISSUE THREAD

**Issue by kdewald** [OpenBluetoothToolbox/SimpleBLE#49]
## Known Issues / To-Do's
- [Linux] Fork safety is not guaranteed.
- [MacOS] Only the main system adapter can be detected.
- [MacOS] Implementation has incomplete error handling and might crash if invalid parameters are passed.
- [MacOS] Timeout logic can be DRYed up.
- [MacOS] Raise exceptions upon error.
- [MacOS] Service and characteristic UUIDs need to be normalized.
- [Windows] Unclear if multiple adapters can be detected.
- [All] Run callbacks in separate threads to prevent blocking internal threads.
- [All] Add a signal handler to ensure all objects are disconnected when the program exits.
- [All] Replace C-style casts with C++ style casts.
- [All] Add Javascript bindings for the library.
- [All] Add Kotlin bindings for the library.

**Comment by jQrgen** [comment]
Hey! I'm wondering how you did the Kotlin bindings.

Is the c++ code accessible from Kotlin(/Native)?
