### ISSUE TITLE
Allow optionally building simpleble, simpleble-static, simple-c, simple-c-static

### ISSUE THREAD

**Issue by ElsterSolutionsOpensource** [OpenBluetoothToolbox/SimpleBLE#60]
It would be useful if the CMakeLists.txt offered options to control which libraries are built: simpleble, simpleble-static, simple-c, simple-c-static. The reason for this is because on the Mac, we build our C++ framework as static libraries, which can be built without specifying a Developer Team. (If built as shared libraries, then the Developer Team has to be specified, and if it is not specified, the build fails). 

The options in CMakeLists.txt could look something like:

option (SIMPLEBLE_STATIC_EXCLUDE "Exclude simpleble-static" OFF)
option (SIMPLEBLE_EXCLUDE "Exclude simpleble" OFF)
option (SIMPLEBLE_C_STATIC_EXCLUDE "Exclude simpleble-c-static" OFF)
option (SIMPLEBLE_C_EXCLUDE "Exclude simpleble-c" OFF)

Then if's applied around each library. 

As an example, I've attached a CMakeLists.txt (from SimpleBLE release  v0.2.0) that I have already modified and tested to do this. 

[CMakeLists.txt](https://github.com/OpenBluetoothToolbox/SimpleBLE/files/8516176/CMakeLists.txt)

**Comment by kdewald** [comment]
Yes! This is something that has already caused quite a bit of controversy, so I'm planning on going over this pretty soon.

**Comment by kdewald** [comment]
Hey @ElsterSolutionsOpensource, wanted to quickly let you know that this has been added to the v0.5 preview,(currently on `feature/next` but soon in `main`. The selection will be based on using CMake's `BUILD_SHARED_LIBS` flag.

**Comment by ElsterSolutionsOpensource** [comment]
Thanks @kdewald!
