### ISSUE TITLE
Cannot subscribe to characteristic

### ISSUE THREAD

**Issue by PatrykSajdok** [OpenBluetoothToolbox/SimpleBLE#9]
I'm trying to read data from few bluetooth devices, for most devices everything works, but for one I cannot subscribe to correct characteristic, because `notify` method in `PeripheralBase` is throwing OperationNotSupported Exception, which is weird because other library I tried was able to read data from the same characteristic. I'm using `notify` example from examples.

**Comment by PatrykSajdok** [comment]
Update: looks like `indicate` method works just fine

**Comment by kdewald** [comment]
@PatrykSajdok thanks for reporting this issue.

You are correct, if you get OperationNotSupported when calling `notify`, it means that the characteristic will probably only support indications. Other library/OS implementations treat both as if they were the same, but for the sake of transparency to the user I try to enforce the right function to be used.
