### ISSUE TITLE
SimplePyBLE and Windows attribute caching

### ISSUE THREAD

**Issue by spkurtzweil** [OpenBluetoothToolbox/SimpleBLE#94]
It seems calling peripheral.read() on a characteristic reads old cached data; reconnecting the device refreshes the data. Would it be possible to add an option to read uncached?

**Comment by kdewald** [comment]
Hey @spkurtzweil, thanks for the report!

This issue has already been fixed in SimpleBLE, but I haven't been able to make a new release for SimplePyBLE yet (I'm almost there, I swear). I'll provide a link to the fixed version once it's out.

**Comment by spkurtzweil** [comment]
Understood. Thanks for the quick response!

**Comment by kdewald** [comment]
Hey @spkurtzweil, just a quick update on this:

I put up a development version with the latest code on `main` that should have this issue fixed. You can find the installation instructions here: https://pypi.org/project/simplepyble/0.0.6.dev3/

Let me know how it goes!

**Comment by spkurtzweil** [comment]
The value does update correctly now. Thank you.
