### ISSUE TITLE
Allow cross compilation

### ISSUE THREAD

**Issue by mikkeldamsgaard** [OpenBluetoothToolbox/SimpleBLE#98]
It looks like the simpleble/CMakeFile uses CMAKE_HOST_SYSTEM_NAME to check the compile target. Could that be changed to CMAKE_SYSTEM_NAME so cross compilation has a chance?

**Comment by kdewald** [comment]
Hey @mikkeldamsgaard, thanks for the suggestion!

This is definitely doable. If you could try it out locally and ensure that no other changes are necessary, I'll be more than happy to merge those changes in.

**Comment by kdewald** [comment]
Hey @mikkeldamsgaard, I just landed this change, so I think it cross-compilation should now work: https://github.com/OpenBluetoothToolbox/SimpleBLE/commit/f54920f24b01e3a79c04770d2bc05616408aa92f
